/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhopcs;

import InterfacesDAO.ProdutoDAO;
import ClasseDAO_EmMemoria.ProdutoDAO_EmMemoria;
import ClasseDAO_EmMemoria.VendaDAO_EmMemoria;
import ClasseDAO_EmMemoria.VendedorDAO_EmMemoria;
import Classes.CalculaComissao;
import Classes.Vendedor;
import InterfacesDAO.VendaDAO;
import InterfacesDAO.VendedorDAO;
import java.awt.FlowLayout;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tainá Leal
 * @author Ana Luiza Leal
 */
public class SistemaComissoes extends javax.swing.JFrame {
     ServicoImportacaoDados servico = new ServicoImportacaoDados();
     ProdutoDAO produtos = new ProdutoDAO_EmMemoria();
     VendedorDAO vendedores = new VendedorDAO_EmMemoria();
     VendaDAO vendas = new VendaDAO_EmMemoria();
     CalculaComissao calcula = new CalculaComissao();
    
     
     
    /**
     * Creates new form SistemaComissoes
     */
    public SistemaComissoes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        aviso = new javax.swing.JOptionPane();
        jFrame1 = new javax.swing.JFrame();
        labelProd = new javax.swing.JLabel();
        labelPreco = new javax.swing.JLabel();
        labelVendedor = new javax.swing.JLabel();
        labelVenda = new javax.swing.JLabel();
        buttonProd = new javax.swing.JButton();
        buttonPreco = new javax.swing.JButton();
        buttonVended = new javax.swing.JButton();
        buttonVenda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textMes = new javax.swing.JTextField();
        textAno = new javax.swing.JTextField();
        textMesInicial = new javax.swing.JTextField();
        textAnoInicial = new javax.swing.JTextField();
        textMesFinal = new javax.swing.JTextField();
        textAnoFinal = new javax.swing.JTextField();
        textMediaMesInicial = new javax.swing.JTextField();
        textMediaAnoInicial = new javax.swing.JTextField();
        textMediaMesFinal = new javax.swing.JTextField();
        textMediaAnoFinal = new javax.swing.JTextField();
        buttonCalculaMes = new javax.swing.JButton();
        buttonCalculaPeriodo = new javax.swing.JButton();
        buttonCalculaMediaPeriodo = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelProd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelProd.setText("Importar dados de Produtos:");
        labelProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelPreco.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelPreco.setText("Importar dados de Preços:");
        labelPreco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelVendedor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelVendedor.setText("Importar dados de Vendedores:");
        labelVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelVenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelVenda.setText("Importar dados de Vendas:");
        labelVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonProd.setText("Selecione o arquivo...");
        buttonProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProdActionPerformed(evt);
            }
        });

        buttonPreco.setText("Selecione o arquivo...");
        buttonPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrecoActionPerformed(evt);
            }
        });

        buttonVended.setText("Selecione o arquivo...");
        buttonVended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVendedActionPerformed(evt);
            }
        });

        buttonVenda.setText("Selecione o arquivo...");
        buttonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVendaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatório de vendas e comissões");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Totais de vendas e comissões no mês:");

        jLabel3.setText("Mês:");

        jLabel4.setText("Ano:");

        jLabel5.setText("Ano Inicial:");

        jLabel6.setText("Mês Inicial:");

        jLabel7.setText("Mês Inicial:");

        jLabel8.setText("Ano Inicial:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Totais de vendas e comissões no período:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Média de vendas e comissões no período:");

        jLabel11.setText("Mês Final:");

        jLabel12.setText("Ano Final:");

        jLabel13.setText("Mês Final:");

        jLabel14.setText("Ano Final:");

        textAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAnoActionPerformed(evt);
            }
        });

        buttonCalculaMes.setText("Calcular");
        buttonCalculaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculaMesActionPerformed(evt);
            }
        });

        buttonCalculaPeriodo.setText("Calcular");
        buttonCalculaPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculaPeriodoActionPerformed(evt);
            }
        });

        buttonCalculaMediaPeriodo.setText("Calcular");
        buttonCalculaMediaPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculaMediaPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAnoFinal)
                                    .addComponent(textAnoInicial)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textMediaMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textMediaMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textMediaAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textMediaAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonCalculaPeriodo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonCalculaMediaPeriodo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonCalculaMes, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(buttonCalculaMes)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCalculaPeriodo)
                .addGap(11, 11, 11)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMediaMesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMediaAnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMediaMesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMediaAnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCalculaMediaPeriodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(buttonPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(buttonVended, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(buttonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(labelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(buttonProd, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelProd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVended, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Acao de cadastrar produtos
    private void buttonProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProdActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try {
            servico.gerenciaImportacaoProdutos(file, produtos);
        } catch (IOException ex) {
          System.out.println("problema no acesso ao arquivo"+file.getAbsolutePath());
        }
    } else {
        System.out.println("Acesso cancelado pelo usuário");
    }
    }//GEN-LAST:event_buttonProdActionPerformed

    //acao de cadastrar precos
    private void buttonPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrecoActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try {
            servico.gerenciaImportacaoPrecos(file, produtos);
        } catch (IOException ex) {
          System.out.println("problema no acesso ao arquivo"+file.getAbsolutePath());
        }
        catch(ParseException ex){
            System.out.println("problema na conversão de valores");
        }
    } else {
        System.out.println("Acesso cancelado pelo usuário");
    }
    }//GEN-LAST:event_buttonPrecoActionPerformed

    //acao de cadatrar vendedores
    private void buttonVendedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVendedActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try {
            servico.gerenciaImportacaoVendedores(file, vendedores);
        } catch (IOException ex) {
          System.out.println("problema no acesso ao arquivo"+file.getAbsolutePath());
        }
    } else {
        System.out.println("Acesso cancelado pelo usuário");
    }
    }//GEN-LAST:event_buttonVendedActionPerformed

    //acao de cadastrar venda
    private void buttonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVendaActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try {
            servico.gerenciaImportacaoVendas(file, produtos, vendedores, vendas);
        } catch (IOException ex) {
          System.out.println("problema no acesso ao arquivo"+file.getAbsolutePath());
        }
        catch(ParseException ex){
            System.out.println("problema na conversão de valores");
        }
    } else {
        System.out.println("Acesso cancelado pelo usuário");
    }
    }//GEN-LAST:event_buttonVendaActionPerformed

    private void textAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAnoActionPerformed

    //acao de calcular as vendas e comissoes do mes e preencher a tabela
    private void buttonCalculaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculaMesActionPerformed
        //checa se existe algum dado inserido
        if (textMes.getText().equals("")||textAno.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Atenção! Digite um valor.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } 
        else{
            double total, comissao;
            
            Set<Vendedor> setVend = vendas.getVendasImportadas().keySet();

            //criacao da tabela atraves do DefaultTableModel
            DefaultTableModel model = new DefaultTableModel();
            JTable tabela = new JTable(model);
            model.addColumn("Nome");
            model.addColumn("Total de vendas");
            model.addColumn("Total de comissão");

            DecimalFormat df = new DecimalFormat("0.00");
           
            Iterator<Vendedor> percorre = setVend.iterator();
            
            /*percorre o conjunto de vendedores calculando a venda e a comissao do periodo indicado.
             * Apos isso armazena os resultados em String[] e adiciona na linha da tabela
             */
            while(percorre.hasNext()){
                Vendedor vende = percorre.next();
                total=vendas.calculaVendaMes(vende, Integer.parseInt(textMes.getText()), Integer.parseInt(textAno.getText()) );
                comissao = calcula.comissaoVendedorMes(vendas, vende, Integer.parseInt(textMes.getText()), Integer.parseInt(textAno.getText()));          
                String[] campos={vende.getNome(), df.format(total), df.format(comissao)};          

                model.addRow(campos);
            }    
            
            //Inicializa um JDialog para mostrar a tabela
            JFrame frame = new JFrame();
            JDialog dialog = new JDialog(frame, "Relatório", true);
            
            JScrollPane pane = new JScrollPane(tabela);
            dialog.getContentPane().setLayout(new FlowLayout());
            dialog.getContentPane().add(pane);  
            dialog.pack();
            dialog.setVisible(true);
              
        }               
    }//GEN-LAST:event_buttonCalculaMesActionPerformed

    //acao de calcular as vendas e comissoes por periodo
    private void buttonCalculaPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculaPeriodoActionPerformed
         
        //testa se os campos foram corretamente inseridos
        if (textMesInicial.getText().equals("")||textAnoInicial.getText().equals("")||
                 textMesFinal.getText().equals("")||textAnoFinal.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Atenção! Digite um valor.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
         
         else{
            double total, comissao;
            
            //criacao da tabela atraves do DefaultTableModel
            DefaultTableModel model = new DefaultTableModel();
            JTable tabela = new JTable(model);
            model.addColumn("Nome");
            model.addColumn("Total de vendas no período");
            model.addColumn("Total de comissão no período");

            
            DecimalFormat df = new DecimalFormat("0.00");
            Set<Vendedor> setVend = vendas.getVendasImportadas().keySet();
            Iterator<Vendedor> percorre = setVend.iterator();
            
            /*percorre o conjunto de vendedores calculando a venda e a comissao do periodo indicado.
             * Apos isso armazena os resultados em String[] e adiciona na linha da tabela
             */
            while(percorre.hasNext()){
                Vendedor vende = percorre.next();
                total=vendas.calculaVendaPeriodo(vende, Integer.parseInt(textMesInicial.getText()), Integer.parseInt(textAnoInicial.getText()),
                        Integer.parseInt(textMesFinal.getText()), Integer.parseInt(textAnoFinal.getText()));
                comissao = calcula.comissaoVendedorPeriodo(vendas, vende, Integer.parseInt(textMesInicial.getText()), Integer.parseInt(textAnoInicial.getText()),
                        Integer.parseInt(textMesFinal.getText()), Integer.parseInt(textAnoFinal.getText()));          
               
                String[] campos={vende.getNome(), df.format(total), df.format(comissao)};          

                model.addRow(campos);
            }    
            
            //Inicializa um JDialog para mostrar a tabela
            JFrame frame = new JFrame();
            JDialog dialog = new JDialog(frame, "Relatório", true);
            
            JScrollPane pane = new JScrollPane(tabela);
            dialog.getContentPane().setLayout(new FlowLayout());
            dialog.getContentPane().add(pane);  
            dialog.pack();
            dialog.setVisible(true);
              
        }              
    }//GEN-LAST:event_buttonCalculaPeriodoActionPerformed

    //acao de calcular media de vendas e comissoes no periodo
    private void buttonCalculaMediaPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculaMediaPeriodoActionPerformed
        if (textMediaMesInicial.getText().equals("")||textMediaAnoInicial.getText().equals("")||
                 textMediaMesFinal.getText().equals("")||textMediaAnoFinal.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Atenção! Digite um valor.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
            double total, comissao;
            
            //criacao da tabela atraves do DefaultTableModel
            DefaultTableModel model = new DefaultTableModel();
            JTable tabela = new JTable(model);
            model.addColumn("Nome");
            model.addColumn("Média de vendas no período");
            model.addColumn("Média de comissão no período");

            
            DecimalFormat df = new DecimalFormat("0.00");
            Set<Vendedor> setVend = vendas.getVendasImportadas().keySet();
            Iterator<Vendedor> percorre = setVend.iterator();
            
            /*percorre o conjunto de vendedores calculando a venda e a comissao do periodo indicado.
             * Apos isso armazena os resultados em String[] e adiciona na linha da tabela
             */
            while(percorre.hasNext()){
                Vendedor vende = percorre.next();
                total=vendas.mediaVendas(vende, Integer.parseInt(textMediaMesInicial.getText()), Integer.parseInt(textMediaAnoInicial.getText()),
                        Integer.parseInt(textMediaMesFinal.getText()), Integer.parseInt(textMediaAnoFinal.getText()));
                comissao = calcula.mediaComissao(vendas, vende, Integer.parseInt(textMediaMesInicial.getText()), Integer.parseInt(textMediaAnoFinal.getText()),
                        Integer.parseInt(textMediaMesFinal.getText()), Integer.parseInt(textMediaAnoFinal.getText()));          
               
                String[] campos={vende.getNome(), df.format(total), df.format(comissao)};          

                model.addRow(campos);
            }    
            
            //Inicializa um JDialog para mostrar a tabela
            JFrame frame = new JFrame();
            JDialog dialog = new JDialog(frame, "Relatório", true);
            
            JScrollPane pane = new JScrollPane(tabela);
            dialog.getContentPane().setLayout(new FlowLayout());
            dialog.getContentPane().add(pane);  
            dialog.pack();
            dialog.setVisible(true);
              
        }              
    }//GEN-LAST:event_buttonCalculaMediaPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaComissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaComissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaComissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaComissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaComissoes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane aviso;
    private javax.swing.JButton buttonCalculaMediaPeriodo;
    private javax.swing.JButton buttonCalculaMes;
    private javax.swing.JButton buttonCalculaPeriodo;
    private javax.swing.JButton buttonPreco;
    private javax.swing.JButton buttonProd;
    private javax.swing.JButton buttonVenda;
    private javax.swing.JButton buttonVended;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelProd;
    private javax.swing.JLabel labelVenda;
    private javax.swing.JLabel labelVendedor;
    private javax.swing.JTextField textAno;
    private javax.swing.JTextField textAnoFinal;
    private javax.swing.JTextField textAnoInicial;
    private javax.swing.JTextField textMediaAnoFinal;
    private javax.swing.JTextField textMediaAnoInicial;
    private javax.swing.JTextField textMediaMesFinal;
    private javax.swing.JTextField textMediaMesInicial;
    private javax.swing.JTextField textMes;
    private javax.swing.JTextField textMesFinal;
    private javax.swing.JTextField textMesInicial;
    // End of variables declaration//GEN-END:variables
}
